# Generated by Django 2.0.2 on 2018-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students_data',
            fields=[
                ('sid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('wmobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=4)),
                ('qualification', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=20)),
            ],
        ),
    ]
